In [1]:
%cd ..

/users/5/dever120/PyGRANSO


# Sphere Manifold

Optimization on a sphere manifold, taken from [this Manopt example](https://www.manopt.org/manifold_documentation_sphere.html)


## Problem Description

Rayleigh quotient problem:
$$\min_{x}-x^TAx,$$
$$\text{s.t. }x^Tx=1,$$
where $A\in R^{n\times n}$ is a symmetric matrix. 

## Modules Importing
Import all necessary modules and add PyGRANSO src folder to system path.

In [2]:
import time
import torch
from pygranso.pygranso import pygranso
from pygranso.pygransoStruct import pygransoStruct

## Data Initialization 
Specify torch device, and generate data

In [3]:
device = torch.device('cpu')
torch.manual_seed(0)
n = 300

# All the user-provided data (vector/matrix/tensor) must be in torch tensor format. 
# As PyTorch tensor is single precision by default, one must explicitly set `dtype=torch.double`.
# Also, please make sure the device of provided torch tensor is the same as opts.torch_device.
A = torch.randn((n, n)).to(device=device, dtype=torch.double)
A = .5 * (A + A.T)

## Function Set-Up

Encode the optimization variables, and objective and constraint functions.

Note: please strictly follow the format of comb_fn, which will be used in the PyGRANSO main algortihm.

In [4]:
# variables and corresponding dimensions.
var_in = {"x": [n, 1]}


def user_fn(X_struct,A):
    x = X_struct.x
    
    # objective function
    f = -x.T @ A @ x

    # inequality constraint, matrix form
    ci = None
    
    # equality constraint 
    ce = pygransoStruct()
    ce.c1 = x.T @ x - 1

    return [f, ci, ce]

comb_fn = lambda X_struct : user_fn(X_struct, A)

## User Options
Specify user-defined options for PyGRANSO

In [5]:
opts = pygransoStruct()
opts.torch_device = device
opts.print_frequency = 10
opts.x0 = torch.randn((n, 1)).to(device=device, dtype=torch.double)
opts.mu0 = 0.1 # increase penalty contribution
opts.opt_tol = 1e-6

## Main Algorithm

In [6]:
start = time.time()
cpu_soln = pygranso(var_spec=var_in, combined_fn=comb_fn, user_opts=opts)
end = time.time()
print("Total Wall Time: {}s".format(end - start))



╔═════ QP SOLVER NOTICE ════════════════════════════════════════════════════════════════════════╗
║  PyGRANSO requires a quadratic program (QP) solver that has a quadprog-compatible interface,  ║
║  the default is osqp. Users may provide their own wrapper for the QP solver.                  ║
║  To disable this notice, set opts.quadprog_info_msg = False                                   ║
╚═══════════════════════════════════════════════════════════════════════════════════════════════╝
═════════════════════════════════════════════════════════════════════════════════════════════════════════════════╗
PyGRANSO: A PyTorch-enabled port of GRANSO with auto-differentiation                                             ║ 
Version 1.2.0                                                                                                    ║ 
Licensed under the AGPLv3, Copyright (C) 2021-2022 Tim Mitchell and Buyun Liang                                  ║ 
═════════════════════════════════════════════

## CUDA Computation

In [7]:
device = torch.device('cuda')
torch.manual_seed(0)
n = 300

# All the user-provided data (vector/matrix/tensor) must be in torch tensor format. 
# As PyTorch tensor is single precision by default, one must explicitly set `dtype=torch.double`.
# Also, please make sure the device of provided torch tensor is the same as opts.torch_device.
A = torch.randn((n, n)).to(device=device, dtype=torch.double)
A = .5 * (A + A.T)

In [8]:
# variables and corresponding dimensions.
var_in = {"x": [n, 1]}


def user_fn(X_struct,A):
    x = X_struct.x
    
    # objective function
    f = -x.T @ A @ x

    # inequality constraint, matrix form
    ci = None
    
    # equality constraint 
    ce = pygransoStruct()
    ce.c1 = x.T @ x - 1

    return [f, ci, ce]

comb_fn = lambda X_struct : user_fn(X_struct, A)

In [9]:
opts = pygransoStruct()
opts.torch_device = device
opts.print_frequency = 10
opts.x0 = torch.randn((n, 1)).to(device=device, dtype=torch.double)
opts.mu0 = 0.1 # increase penalty contribution
opts.opt_tol = 1e-6

In [10]:
start = time.time()
cuda_soln = pygranso(var_spec=var_in, combined_fn=comb_fn, user_opts=opts)
end = time.time()
print("Total Wall Time: {}s".format(end - start))

/users/5/dever120/PyGRANSO/.venv/lib/python3.13/site-packages/torch/autograd/graph.py:829: UserWarning: Attempting to run cuBLAS, but there was no current CUDA context! Attempting to set the primary context... (Triggered internally at /pytorch/aten/src/ATen/cuda/CublasHandlePool.cpp:179.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass




╔═════ QP SOLVER NOTICE ════════════════════════════════════════════════════════════════════════╗
║  PyGRANSO requires a quadratic program (QP) solver that has a quadprog-compatible interface,  ║
║  the default is osqp. Users may provide their own wrapper for the QP solver.                  ║
║  To disable this notice, set opts.quadprog_info_msg = False                                   ║
╚═══════════════════════════════════════════════════════════════════════════════════════════════╝
═════════════════════════════════════════════════════════════════════════════════════════════════════════════════╗
PyGRANSO: A PyTorch-enabled port of GRANSO with auto-differentiation                                             ║ 
Version 1.2.0                                                                                                    ║ 
Licensed under the AGPLv3, Copyright (C) 2021-2022 Tim Mitchell and Buyun Liang                                  ║ 
═════════════════════════════════════════════

## Testing

In [31]:
torch.testing.assert_close(
    cpu_soln.final.x,
    cuda_soln.final.x.cpu(),
    atol=1e-2,
    rtol=1e-2,
)

In [24]:
torch.argmax(torch.abs(cpu_soln.final.x - cuda_soln.final.x.cpu()))

tensor(234)

In [25]:
cpu_soln.final.x[:10]

tensor([[-0.0546],
        [ 0.0525],
        [ 0.0128],
        [ 0.0364],
        [-0.0574],
        [-0.0208],
        [ 0.0452],
        [ 0.0742],
        [-0.1247],
        [-0.0928]], dtype=torch.float64)

In [26]:
cuda_soln.final.x.cpu()[:10]

tensor([[-0.0547],
        [ 0.0518],
        [ 0.0133],
        [ 0.0362],
        [-0.0568],
        [-0.0208],
        [ 0.0456],
        [ 0.0739],
        [-0.1250],
        [-0.0925]], dtype=torch.float64)

In [27]:
cpu_soln.final.x[234]

tensor([-0.0535], dtype=torch.float64)

In [28]:
cuda_soln.final.x.cpu()[234]

tensor([-0.0523], dtype=torch.float64)